//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controlador.EntradaWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entrada", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Entrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EntradaWS.EntradaWSSoap")]
    public interface EntradaWSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listarEntradasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarEntradas", ReplyAction="*")]
        Controlador.EntradaWS.listarEntradasResponse listarEntradas(Controlador.EntradaWS.listarEntradasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarEntradas", ReplyAction="*")]
        System.Threading.Tasks.Task<Controlador.EntradaWS.listarEntradasResponse> listarEntradasAsync(Controlador.EntradaWS.listarEntradasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarEntradasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarEntradas", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.EntradaWS.listarEntradasRequestBody Body;
        
        public listarEntradasRequest() {
        }
        
        public listarEntradasRequest(Controlador.EntradaWS.listarEntradasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarEntradasRequestBody {
        
        public listarEntradasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarEntradasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarEntradasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.EntradaWS.listarEntradasResponseBody Body;
        
        public listarEntradasResponse() {
        }
        
        public listarEntradasResponse(Controlador.EntradaWS.listarEntradasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarEntradasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controlador.EntradaWS.Entrada[] listarEntradasResult;
        
        public listarEntradasResponseBody() {
        }
        
        public listarEntradasResponseBody(Controlador.EntradaWS.Entrada[] listarEntradasResult) {
            this.listarEntradasResult = listarEntradasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EntradaWSSoapChannel : Controlador.EntradaWS.EntradaWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntradaWSSoapClient : System.ServiceModel.ClientBase<Controlador.EntradaWS.EntradaWSSoap>, Controlador.EntradaWS.EntradaWSSoap {
        
        public EntradaWSSoapClient() {
        }
        
        public EntradaWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntradaWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntradaWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntradaWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controlador.EntradaWS.listarEntradasResponse Controlador.EntradaWS.EntradaWSSoap.listarEntradas(Controlador.EntradaWS.listarEntradasRequest request) {
            return base.Channel.listarEntradas(request);
        }
        
        public Controlador.EntradaWS.Entrada[] listarEntradas() {
            Controlador.EntradaWS.listarEntradasRequest inValue = new Controlador.EntradaWS.listarEntradasRequest();
            inValue.Body = new Controlador.EntradaWS.listarEntradasRequestBody();
            Controlador.EntradaWS.listarEntradasResponse retVal = ((Controlador.EntradaWS.EntradaWSSoap)(this)).listarEntradas(inValue);
            return retVal.Body.listarEntradasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controlador.EntradaWS.listarEntradasResponse> Controlador.EntradaWS.EntradaWSSoap.listarEntradasAsync(Controlador.EntradaWS.listarEntradasRequest request) {
            return base.Channel.listarEntradasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controlador.EntradaWS.listarEntradasResponse> listarEntradasAsync() {
            Controlador.EntradaWS.listarEntradasRequest inValue = new Controlador.EntradaWS.listarEntradasRequest();
            inValue.Body = new Controlador.EntradaWS.listarEntradasRequestBody();
            return ((Controlador.EntradaWS.EntradaWSSoap)(this)).listarEntradasAsync(inValue);
        }
    }
}
