//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controlador.DetalleOrdenWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orden_Menu_Detalle", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Orden_Menu_Detalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Controlador.DetalleOrdenWS.Entrada EntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Controlador.DetalleOrdenWS.PlatoFondo PlatoFondoField;
        
        private int IdOrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Controlador.DetalleOrdenWS.Entrada Entrada {
            get {
                return this.EntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.EntradaField, value) != true)) {
                    this.EntradaField = value;
                    this.RaisePropertyChanged("Entrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Controlador.DetalleOrdenWS.PlatoFondo PlatoFondo {
            get {
                return this.PlatoFondoField;
            }
            set {
                if ((object.ReferenceEquals(this.PlatoFondoField, value) != true)) {
                    this.PlatoFondoField = value;
                    this.RaisePropertyChanged("PlatoFondo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int IdOrden {
            get {
                return this.IdOrdenField;
            }
            set {
                if ((this.IdOrdenField.Equals(value) != true)) {
                    this.IdOrdenField = value;
                    this.RaisePropertyChanged("IdOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entrada", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Entrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlatoFondo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PlatoFondo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private double PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DetalleOrdenWS.Orden_Menu_DetalleWSSoap")]
    public interface Orden_Menu_DetalleWSSoap {
        
        // CODEGEN: Generating message contract since element name listarDetallePedidosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarDetallePedidos", ReplyAction="*")]
        Controlador.DetalleOrdenWS.listarDetallePedidosResponse listarDetallePedidos(Controlador.DetalleOrdenWS.listarDetallePedidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarDetallePedidos", ReplyAction="*")]
        System.Threading.Tasks.Task<Controlador.DetalleOrdenWS.listarDetallePedidosResponse> listarDetallePedidosAsync(Controlador.DetalleOrdenWS.listarDetallePedidosRequest request);
        
        // CODEGEN: Generating message contract since element name o from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarDetalleDeOrden", ReplyAction="*")]
        Controlador.DetalleOrdenWS.registrarDetalleDeOrdenResponse registrarDetalleDeOrden(Controlador.DetalleOrdenWS.registrarDetalleDeOrdenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarDetalleDeOrden", ReplyAction="*")]
        System.Threading.Tasks.Task<Controlador.DetalleOrdenWS.registrarDetalleDeOrdenResponse> registrarDetalleDeOrdenAsync(Controlador.DetalleOrdenWS.registrarDetalleDeOrdenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarDetallePedidosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarDetallePedidos", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.DetalleOrdenWS.listarDetallePedidosRequestBody Body;
        
        public listarDetallePedidosRequest() {
        }
        
        public listarDetallePedidosRequest(Controlador.DetalleOrdenWS.listarDetallePedidosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarDetallePedidosRequestBody {
        
        public listarDetallePedidosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarDetallePedidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarDetallePedidosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.DetalleOrdenWS.listarDetallePedidosResponseBody Body;
        
        public listarDetallePedidosResponse() {
        }
        
        public listarDetallePedidosResponse(Controlador.DetalleOrdenWS.listarDetallePedidosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarDetallePedidosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controlador.DetalleOrdenWS.Orden_Menu_Detalle[] listarDetallePedidosResult;
        
        public listarDetallePedidosResponseBody() {
        }
        
        public listarDetallePedidosResponseBody(Controlador.DetalleOrdenWS.Orden_Menu_Detalle[] listarDetallePedidosResult) {
            this.listarDetallePedidosResult = listarDetallePedidosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarDetalleDeOrdenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarDetalleDeOrden", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.DetalleOrdenWS.registrarDetalleDeOrdenRequestBody Body;
        
        public registrarDetalleDeOrdenRequest() {
        }
        
        public registrarDetalleDeOrdenRequest(Controlador.DetalleOrdenWS.registrarDetalleDeOrdenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarDetalleDeOrdenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controlador.DetalleOrdenWS.Orden_Menu_Detalle o;
        
        public registrarDetalleDeOrdenRequestBody() {
        }
        
        public registrarDetalleDeOrdenRequestBody(Controlador.DetalleOrdenWS.Orden_Menu_Detalle o) {
            this.o = o;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarDetalleDeOrdenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarDetalleDeOrdenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.DetalleOrdenWS.registrarDetalleDeOrdenResponseBody Body;
        
        public registrarDetalleDeOrdenResponse() {
        }
        
        public registrarDetalleDeOrdenResponse(Controlador.DetalleOrdenWS.registrarDetalleDeOrdenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarDetalleDeOrdenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool registrarDetalleDeOrdenResult;
        
        public registrarDetalleDeOrdenResponseBody() {
        }
        
        public registrarDetalleDeOrdenResponseBody(bool registrarDetalleDeOrdenResult) {
            this.registrarDetalleDeOrdenResult = registrarDetalleDeOrdenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Orden_Menu_DetalleWSSoapChannel : Controlador.DetalleOrdenWS.Orden_Menu_DetalleWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Orden_Menu_DetalleWSSoapClient : System.ServiceModel.ClientBase<Controlador.DetalleOrdenWS.Orden_Menu_DetalleWSSoap>, Controlador.DetalleOrdenWS.Orden_Menu_DetalleWSSoap {
        
        public Orden_Menu_DetalleWSSoapClient() {
        }
        
        public Orden_Menu_DetalleWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Orden_Menu_DetalleWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Orden_Menu_DetalleWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Orden_Menu_DetalleWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controlador.DetalleOrdenWS.listarDetallePedidosResponse Controlador.DetalleOrdenWS.Orden_Menu_DetalleWSSoap.listarDetallePedidos(Controlador.DetalleOrdenWS.listarDetallePedidosRequest request) {
            return base.Channel.listarDetallePedidos(request);
        }
        
        public Controlador.DetalleOrdenWS.Orden_Menu_Detalle[] listarDetallePedidos() {
            Controlador.DetalleOrdenWS.listarDetallePedidosRequest inValue = new Controlador.DetalleOrdenWS.listarDetallePedidosRequest();
            inValue.Body = new Controlador.DetalleOrdenWS.listarDetallePedidosRequestBody();
            Controlador.DetalleOrdenWS.listarDetallePedidosResponse retVal = ((Controlador.DetalleOrdenWS.Orden_Menu_DetalleWSSoap)(this)).listarDetallePedidos(inValue);
            return retVal.Body.listarDetallePedidosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controlador.DetalleOrdenWS.listarDetallePedidosResponse> Controlador.DetalleOrdenWS.Orden_Menu_DetalleWSSoap.listarDetallePedidosAsync(Controlador.DetalleOrdenWS.listarDetallePedidosRequest request) {
            return base.Channel.listarDetallePedidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controlador.DetalleOrdenWS.listarDetallePedidosResponse> listarDetallePedidosAsync() {
            Controlador.DetalleOrdenWS.listarDetallePedidosRequest inValue = new Controlador.DetalleOrdenWS.listarDetallePedidosRequest();
            inValue.Body = new Controlador.DetalleOrdenWS.listarDetallePedidosRequestBody();
            return ((Controlador.DetalleOrdenWS.Orden_Menu_DetalleWSSoap)(this)).listarDetallePedidosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controlador.DetalleOrdenWS.registrarDetalleDeOrdenResponse Controlador.DetalleOrdenWS.Orden_Menu_DetalleWSSoap.registrarDetalleDeOrden(Controlador.DetalleOrdenWS.registrarDetalleDeOrdenRequest request) {
            return base.Channel.registrarDetalleDeOrden(request);
        }
        
        public bool registrarDetalleDeOrden(Controlador.DetalleOrdenWS.Orden_Menu_Detalle o) {
            Controlador.DetalleOrdenWS.registrarDetalleDeOrdenRequest inValue = new Controlador.DetalleOrdenWS.registrarDetalleDeOrdenRequest();
            inValue.Body = new Controlador.DetalleOrdenWS.registrarDetalleDeOrdenRequestBody();
            inValue.Body.o = o;
            Controlador.DetalleOrdenWS.registrarDetalleDeOrdenResponse retVal = ((Controlador.DetalleOrdenWS.Orden_Menu_DetalleWSSoap)(this)).registrarDetalleDeOrden(inValue);
            return retVal.Body.registrarDetalleDeOrdenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controlador.DetalleOrdenWS.registrarDetalleDeOrdenResponse> Controlador.DetalleOrdenWS.Orden_Menu_DetalleWSSoap.registrarDetalleDeOrdenAsync(Controlador.DetalleOrdenWS.registrarDetalleDeOrdenRequest request) {
            return base.Channel.registrarDetalleDeOrdenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controlador.DetalleOrdenWS.registrarDetalleDeOrdenResponse> registrarDetalleDeOrdenAsync(Controlador.DetalleOrdenWS.Orden_Menu_Detalle o) {
            Controlador.DetalleOrdenWS.registrarDetalleDeOrdenRequest inValue = new Controlador.DetalleOrdenWS.registrarDetalleDeOrdenRequest();
            inValue.Body = new Controlador.DetalleOrdenWS.registrarDetalleDeOrdenRequestBody();
            inValue.Body.o = o;
            return ((Controlador.DetalleOrdenWS.Orden_Menu_DetalleWSSoap)(this)).registrarDetalleDeOrdenAsync(inValue);
        }
    }
}
