//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controlador.OrdenWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orden", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Orden : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Controlador.OrdenWS.Mesa MesaField;
        
        private System.DateTime Hora_ordenField;
        
        private double PreioTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Controlador.OrdenWS.Orden_Menu_Detalle[] DetalleOrdenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Controlador.OrdenWS.Mesa Mesa {
            get {
                return this.MesaField;
            }
            set {
                if ((object.ReferenceEquals(this.MesaField, value) != true)) {
                    this.MesaField = value;
                    this.RaisePropertyChanged("Mesa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Hora_orden {
            get {
                return this.Hora_ordenField;
            }
            set {
                if ((this.Hora_ordenField.Equals(value) != true)) {
                    this.Hora_ordenField = value;
                    this.RaisePropertyChanged("Hora_orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double PreioTotal {
            get {
                return this.PreioTotalField;
            }
            set {
                if ((this.PreioTotalField.Equals(value) != true)) {
                    this.PreioTotalField = value;
                    this.RaisePropertyChanged("PreioTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Controlador.OrdenWS.Orden_Menu_Detalle[] DetalleOrden {
            get {
                return this.DetalleOrdenField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleOrdenField, value) != true)) {
                    this.DetalleOrdenField = value;
                    this.RaisePropertyChanged("DetalleOrden");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mesa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Mesa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int CapacidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Capacidad {
            get {
                return this.CapacidadField;
            }
            set {
                if ((this.CapacidadField.Equals(value) != true)) {
                    this.CapacidadField = value;
                    this.RaisePropertyChanged("Capacidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orden_Menu_Detalle", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Orden_Menu_Detalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Controlador.OrdenWS.Entrada EntradaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Controlador.OrdenWS.PlatoFondo PlatoFondoField;
        
        private int IdOrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Controlador.OrdenWS.Entrada Entrada {
            get {
                return this.EntradaField;
            }
            set {
                if ((object.ReferenceEquals(this.EntradaField, value) != true)) {
                    this.EntradaField = value;
                    this.RaisePropertyChanged("Entrada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Controlador.OrdenWS.PlatoFondo PlatoFondo {
            get {
                return this.PlatoFondoField;
            }
            set {
                if ((object.ReferenceEquals(this.PlatoFondoField, value) != true)) {
                    this.PlatoFondoField = value;
                    this.RaisePropertyChanged("PlatoFondo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int IdOrden {
            get {
                return this.IdOrdenField;
            }
            set {
                if ((this.IdOrdenField.Equals(value) != true)) {
                    this.IdOrdenField = value;
                    this.RaisePropertyChanged("IdOrden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Texto {
            get {
                return this.TextoField;
            }
            set {
                if ((object.ReferenceEquals(this.TextoField, value) != true)) {
                    this.TextoField = value;
                    this.RaisePropertyChanged("Texto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Entrada", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Entrada : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlatoFondo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PlatoFondo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private double PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrdenWS.OrdenWSSoap")]
    public interface OrdenWSSoap {
        
        // CODEGEN: Generating message contract since element name listarDetallePedidosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarDetallePedidos", ReplyAction="*")]
        Controlador.OrdenWS.listarDetallePedidosResponse listarDetallePedidos(Controlador.OrdenWS.listarDetallePedidosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarDetallePedidos", ReplyAction="*")]
        System.Threading.Tasks.Task<Controlador.OrdenWS.listarDetallePedidosResponse> listarDetallePedidosAsync(Controlador.OrdenWS.listarDetallePedidosRequest request);
        
        // CODEGEN: Generating message contract since element name o from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarOrden", ReplyAction="*")]
        Controlador.OrdenWS.registrarOrdenResponse registrarOrden(Controlador.OrdenWS.registrarOrdenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrarOrden", ReplyAction="*")]
        System.Threading.Tasks.Task<Controlador.OrdenWS.registrarOrdenResponse> registrarOrdenAsync(Controlador.OrdenWS.registrarOrdenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarDetallePedidosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarDetallePedidos", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.OrdenWS.listarDetallePedidosRequestBody Body;
        
        public listarDetallePedidosRequest() {
        }
        
        public listarDetallePedidosRequest(Controlador.OrdenWS.listarDetallePedidosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarDetallePedidosRequestBody {
        
        public listarDetallePedidosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarDetallePedidosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarDetallePedidosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.OrdenWS.listarDetallePedidosResponseBody Body;
        
        public listarDetallePedidosResponse() {
        }
        
        public listarDetallePedidosResponse(Controlador.OrdenWS.listarDetallePedidosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarDetallePedidosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controlador.OrdenWS.Orden[] listarDetallePedidosResult;
        
        public listarDetallePedidosResponseBody() {
        }
        
        public listarDetallePedidosResponseBody(Controlador.OrdenWS.Orden[] listarDetallePedidosResult) {
            this.listarDetallePedidosResult = listarDetallePedidosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarOrdenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarOrden", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.OrdenWS.registrarOrdenRequestBody Body;
        
        public registrarOrdenRequest() {
        }
        
        public registrarOrdenRequest(Controlador.OrdenWS.registrarOrdenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarOrdenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controlador.OrdenWS.Orden o;
        
        public registrarOrdenRequestBody() {
        }
        
        public registrarOrdenRequestBody(Controlador.OrdenWS.Orden o) {
            this.o = o;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarOrdenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarOrdenResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.OrdenWS.registrarOrdenResponseBody Body;
        
        public registrarOrdenResponse() {
        }
        
        public registrarOrdenResponse(Controlador.OrdenWS.registrarOrdenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarOrdenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool registrarOrdenResult;
        
        public registrarOrdenResponseBody() {
        }
        
        public registrarOrdenResponseBody(bool registrarOrdenResult) {
            this.registrarOrdenResult = registrarOrdenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdenWSSoapChannel : Controlador.OrdenWS.OrdenWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenWSSoapClient : System.ServiceModel.ClientBase<Controlador.OrdenWS.OrdenWSSoap>, Controlador.OrdenWS.OrdenWSSoap {
        
        public OrdenWSSoapClient() {
        }
        
        public OrdenWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controlador.OrdenWS.listarDetallePedidosResponse Controlador.OrdenWS.OrdenWSSoap.listarDetallePedidos(Controlador.OrdenWS.listarDetallePedidosRequest request) {
            return base.Channel.listarDetallePedidos(request);
        }
        
        public Controlador.OrdenWS.Orden[] listarDetallePedidos() {
            Controlador.OrdenWS.listarDetallePedidosRequest inValue = new Controlador.OrdenWS.listarDetallePedidosRequest();
            inValue.Body = new Controlador.OrdenWS.listarDetallePedidosRequestBody();
            Controlador.OrdenWS.listarDetallePedidosResponse retVal = ((Controlador.OrdenWS.OrdenWSSoap)(this)).listarDetallePedidos(inValue);
            return retVal.Body.listarDetallePedidosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controlador.OrdenWS.listarDetallePedidosResponse> Controlador.OrdenWS.OrdenWSSoap.listarDetallePedidosAsync(Controlador.OrdenWS.listarDetallePedidosRequest request) {
            return base.Channel.listarDetallePedidosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controlador.OrdenWS.listarDetallePedidosResponse> listarDetallePedidosAsync() {
            Controlador.OrdenWS.listarDetallePedidosRequest inValue = new Controlador.OrdenWS.listarDetallePedidosRequest();
            inValue.Body = new Controlador.OrdenWS.listarDetallePedidosRequestBody();
            return ((Controlador.OrdenWS.OrdenWSSoap)(this)).listarDetallePedidosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controlador.OrdenWS.registrarOrdenResponse Controlador.OrdenWS.OrdenWSSoap.registrarOrden(Controlador.OrdenWS.registrarOrdenRequest request) {
            return base.Channel.registrarOrden(request);
        }
        
        public bool registrarOrden(Controlador.OrdenWS.Orden o) {
            Controlador.OrdenWS.registrarOrdenRequest inValue = new Controlador.OrdenWS.registrarOrdenRequest();
            inValue.Body = new Controlador.OrdenWS.registrarOrdenRequestBody();
            inValue.Body.o = o;
            Controlador.OrdenWS.registrarOrdenResponse retVal = ((Controlador.OrdenWS.OrdenWSSoap)(this)).registrarOrden(inValue);
            return retVal.Body.registrarOrdenResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controlador.OrdenWS.registrarOrdenResponse> Controlador.OrdenWS.OrdenWSSoap.registrarOrdenAsync(Controlador.OrdenWS.registrarOrdenRequest request) {
            return base.Channel.registrarOrdenAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controlador.OrdenWS.registrarOrdenResponse> registrarOrdenAsync(Controlador.OrdenWS.Orden o) {
            Controlador.OrdenWS.registrarOrdenRequest inValue = new Controlador.OrdenWS.registrarOrdenRequest();
            inValue.Body = new Controlador.OrdenWS.registrarOrdenRequestBody();
            inValue.Body.o = o;
            return ((Controlador.OrdenWS.OrdenWSSoap)(this)).registrarOrdenAsync(inValue);
        }
    }
}
