//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp12.PlatoFondoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlatoFondoWS.Plato_FondoWSSoap")]
    public interface Plato_FondoWSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listarEntradasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarEntradas", ReplyAction="*")]
        WindowsFormsApp12.PlatoFondoWS.listarEntradasResponse listarEntradas(WindowsFormsApp12.PlatoFondoWS.listarEntradasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarEntradas", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp12.PlatoFondoWS.listarEntradasResponse> listarEntradasAsync(WindowsFormsApp12.PlatoFondoWS.listarEntradasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarEntradasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarEntradas", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp12.PlatoFondoWS.listarEntradasRequestBody Body;
        
        public listarEntradasRequest() {
        }
        
        public listarEntradasRequest(WindowsFormsApp12.PlatoFondoWS.listarEntradasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarEntradasRequestBody {
        
        public listarEntradasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarEntradasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarEntradasResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp12.PlatoFondoWS.listarEntradasResponseBody Body;
        
        public listarEntradasResponse() {
        }
        
        public listarEntradasResponse(WindowsFormsApp12.PlatoFondoWS.listarEntradasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarEntradasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controlador.PlatoFondoWS.PlatoFondo[] listarEntradasResult;
        
        public listarEntradasResponseBody() {
        }
        
        public listarEntradasResponseBody(Controlador.PlatoFondoWS.PlatoFondo[] listarEntradasResult) {
            this.listarEntradasResult = listarEntradasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Plato_FondoWSSoapChannel : WindowsFormsApp12.PlatoFondoWS.Plato_FondoWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Plato_FondoWSSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp12.PlatoFondoWS.Plato_FondoWSSoap>, WindowsFormsApp12.PlatoFondoWS.Plato_FondoWSSoap {
        
        public Plato_FondoWSSoapClient() {
        }
        
        public Plato_FondoWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Plato_FondoWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Plato_FondoWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Plato_FondoWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp12.PlatoFondoWS.listarEntradasResponse WindowsFormsApp12.PlatoFondoWS.Plato_FondoWSSoap.listarEntradas(WindowsFormsApp12.PlatoFondoWS.listarEntradasRequest request) {
            return base.Channel.listarEntradas(request);
        }
        
        public Controlador.PlatoFondoWS.PlatoFondo[] listarEntradas() {
            WindowsFormsApp12.PlatoFondoWS.listarEntradasRequest inValue = new WindowsFormsApp12.PlatoFondoWS.listarEntradasRequest();
            inValue.Body = new WindowsFormsApp12.PlatoFondoWS.listarEntradasRequestBody();
            WindowsFormsApp12.PlatoFondoWS.listarEntradasResponse retVal = ((WindowsFormsApp12.PlatoFondoWS.Plato_FondoWSSoap)(this)).listarEntradas(inValue);
            return retVal.Body.listarEntradasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp12.PlatoFondoWS.listarEntradasResponse> WindowsFormsApp12.PlatoFondoWS.Plato_FondoWSSoap.listarEntradasAsync(WindowsFormsApp12.PlatoFondoWS.listarEntradasRequest request) {
            return base.Channel.listarEntradasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp12.PlatoFondoWS.listarEntradasResponse> listarEntradasAsync() {
            WindowsFormsApp12.PlatoFondoWS.listarEntradasRequest inValue = new WindowsFormsApp12.PlatoFondoWS.listarEntradasRequest();
            inValue.Body = new WindowsFormsApp12.PlatoFondoWS.listarEntradasRequestBody();
            return ((WindowsFormsApp12.PlatoFondoWS.Plato_FondoWSSoap)(this)).listarEntradasAsync(inValue);
        }
    }
}
