//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp12.EntradaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EntradaWS.EntradaWSSoap")]
    public interface EntradaWSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento listarEntradasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarEntradas", ReplyAction="*")]
        WindowsFormsApp12.EntradaWS.listarEntradasResponse listarEntradas(WindowsFormsApp12.EntradaWS.listarEntradasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarEntradas", ReplyAction="*")]
        System.Threading.Tasks.Task<WindowsFormsApp12.EntradaWS.listarEntradasResponse> listarEntradasAsync(WindowsFormsApp12.EntradaWS.listarEntradasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarEntradasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarEntradas", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp12.EntradaWS.listarEntradasRequestBody Body;
        
        public listarEntradasRequest() {
        }
        
        public listarEntradasRequest(WindowsFormsApp12.EntradaWS.listarEntradasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarEntradasRequestBody {
        
        public listarEntradasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarEntradasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarEntradasResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApp12.EntradaWS.listarEntradasResponseBody Body;
        
        public listarEntradasResponse() {
        }
        
        public listarEntradasResponse(WindowsFormsApp12.EntradaWS.listarEntradasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarEntradasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controlador.EntradaWS.Entrada[] listarEntradasResult;
        
        public listarEntradasResponseBody() {
        }
        
        public listarEntradasResponseBody(Controlador.EntradaWS.Entrada[] listarEntradasResult) {
            this.listarEntradasResult = listarEntradasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EntradaWSSoapChannel : WindowsFormsApp12.EntradaWS.EntradaWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EntradaWSSoapClient : System.ServiceModel.ClientBase<WindowsFormsApp12.EntradaWS.EntradaWSSoap>, WindowsFormsApp12.EntradaWS.EntradaWSSoap {
        
        public EntradaWSSoapClient() {
        }
        
        public EntradaWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EntradaWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntradaWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EntradaWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp12.EntradaWS.listarEntradasResponse WindowsFormsApp12.EntradaWS.EntradaWSSoap.listarEntradas(WindowsFormsApp12.EntradaWS.listarEntradasRequest request) {
            return base.Channel.listarEntradas(request);
        }
        
        public Controlador.EntradaWS.Entrada[] listarEntradas() {
            WindowsFormsApp12.EntradaWS.listarEntradasRequest inValue = new WindowsFormsApp12.EntradaWS.listarEntradasRequest();
            inValue.Body = new WindowsFormsApp12.EntradaWS.listarEntradasRequestBody();
            WindowsFormsApp12.EntradaWS.listarEntradasResponse retVal = ((WindowsFormsApp12.EntradaWS.EntradaWSSoap)(this)).listarEntradas(inValue);
            return retVal.Body.listarEntradasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp12.EntradaWS.listarEntradasResponse> WindowsFormsApp12.EntradaWS.EntradaWSSoap.listarEntradasAsync(WindowsFormsApp12.EntradaWS.listarEntradasRequest request) {
            return base.Channel.listarEntradasAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp12.EntradaWS.listarEntradasResponse> listarEntradasAsync() {
            WindowsFormsApp12.EntradaWS.listarEntradasRequest inValue = new WindowsFormsApp12.EntradaWS.listarEntradasRequest();
            inValue.Body = new WindowsFormsApp12.EntradaWS.listarEntradasRequestBody();
            return ((WindowsFormsApp12.EntradaWS.EntradaWSSoap)(this)).listarEntradasAsync(inValue);
        }
    }
}
