//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controlador.MesaWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mesa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Mesa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int CapacidadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Capacidad {
            get {
                return this.CapacidadField;
            }
            set {
                if ((this.CapacidadField.Equals(value) != true)) {
                    this.CapacidadField = value;
                    this.RaisePropertyChanged("Capacidad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MesaWS.MesaWSSoap")]
    public interface MesaWSSoap {
        
        // CODEGEN: Generating message contract since element name listarMesasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarMesas", ReplyAction="*")]
        Controlador.MesaWS.listarMesasResponse listarMesas(Controlador.MesaWS.listarMesasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarMesas", ReplyAction="*")]
        System.Threading.Tasks.Task<Controlador.MesaWS.listarMesasResponse> listarMesasAsync(Controlador.MesaWS.listarMesasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarMesasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarMesas", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.MesaWS.listarMesasRequestBody Body;
        
        public listarMesasRequest() {
        }
        
        public listarMesasRequest(Controlador.MesaWS.listarMesasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarMesasRequestBody {
        
        public listarMesasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarMesasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarMesasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.MesaWS.listarMesasResponseBody Body;
        
        public listarMesasResponse() {
        }
        
        public listarMesasResponse(Controlador.MesaWS.listarMesasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarMesasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controlador.MesaWS.Mesa[] listarMesasResult;
        
        public listarMesasResponseBody() {
        }
        
        public listarMesasResponseBody(Controlador.MesaWS.Mesa[] listarMesasResult) {
            this.listarMesasResult = listarMesasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MesaWSSoapChannel : Controlador.MesaWS.MesaWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaWSSoapClient : System.ServiceModel.ClientBase<Controlador.MesaWS.MesaWSSoap>, Controlador.MesaWS.MesaWSSoap {
        
        public MesaWSSoapClient() {
        }
        
        public MesaWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MesaWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesaWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesaWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controlador.MesaWS.listarMesasResponse Controlador.MesaWS.MesaWSSoap.listarMesas(Controlador.MesaWS.listarMesasRequest request) {
            return base.Channel.listarMesas(request);
        }
        
        public Controlador.MesaWS.Mesa[] listarMesas() {
            Controlador.MesaWS.listarMesasRequest inValue = new Controlador.MesaWS.listarMesasRequest();
            inValue.Body = new Controlador.MesaWS.listarMesasRequestBody();
            Controlador.MesaWS.listarMesasResponse retVal = ((Controlador.MesaWS.MesaWSSoap)(this)).listarMesas(inValue);
            return retVal.Body.listarMesasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controlador.MesaWS.listarMesasResponse> Controlador.MesaWS.MesaWSSoap.listarMesasAsync(Controlador.MesaWS.listarMesasRequest request) {
            return base.Channel.listarMesasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controlador.MesaWS.listarMesasResponse> listarMesasAsync() {
            Controlador.MesaWS.listarMesasRequest inValue = new Controlador.MesaWS.listarMesasRequest();
            inValue.Body = new Controlador.MesaWS.listarMesasRequestBody();
            return ((Controlador.MesaWS.MesaWSSoap)(this)).listarMesasAsync(inValue);
        }
    }
}
