//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Controlador.PlatoFondoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlatoFondo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PlatoFondo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private double PrecioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PlatoFondoWS.Plato_FondoWSSoap")]
    public interface Plato_FondoWSSoap {
        
        // CODEGEN: Generating message contract since element name listarPlatoFondoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarPlatoFondo", ReplyAction="*")]
        Controlador.PlatoFondoWS.listarPlatoFondoResponse listarPlatoFondo(Controlador.PlatoFondoWS.listarPlatoFondoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/listarPlatoFondo", ReplyAction="*")]
        System.Threading.Tasks.Task<Controlador.PlatoFondoWS.listarPlatoFondoResponse> listarPlatoFondoAsync(Controlador.PlatoFondoWS.listarPlatoFondoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarPlatoFondoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarPlatoFondo", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.PlatoFondoWS.listarPlatoFondoRequestBody Body;
        
        public listarPlatoFondoRequest() {
        }
        
        public listarPlatoFondoRequest(Controlador.PlatoFondoWS.listarPlatoFondoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class listarPlatoFondoRequestBody {
        
        public listarPlatoFondoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class listarPlatoFondoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="listarPlatoFondoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Controlador.PlatoFondoWS.listarPlatoFondoResponseBody Body;
        
        public listarPlatoFondoResponse() {
        }
        
        public listarPlatoFondoResponse(Controlador.PlatoFondoWS.listarPlatoFondoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class listarPlatoFondoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Controlador.PlatoFondoWS.PlatoFondo[] listarPlatoFondoResult;
        
        public listarPlatoFondoResponseBody() {
        }
        
        public listarPlatoFondoResponseBody(Controlador.PlatoFondoWS.PlatoFondo[] listarPlatoFondoResult) {
            this.listarPlatoFondoResult = listarPlatoFondoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Plato_FondoWSSoapChannel : Controlador.PlatoFondoWS.Plato_FondoWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Plato_FondoWSSoapClient : System.ServiceModel.ClientBase<Controlador.PlatoFondoWS.Plato_FondoWSSoap>, Controlador.PlatoFondoWS.Plato_FondoWSSoap {
        
        public Plato_FondoWSSoapClient() {
        }
        
        public Plato_FondoWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Plato_FondoWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Plato_FondoWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Plato_FondoWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Controlador.PlatoFondoWS.listarPlatoFondoResponse Controlador.PlatoFondoWS.Plato_FondoWSSoap.listarPlatoFondo(Controlador.PlatoFondoWS.listarPlatoFondoRequest request) {
            return base.Channel.listarPlatoFondo(request);
        }
        
        public Controlador.PlatoFondoWS.PlatoFondo[] listarPlatoFondo() {
            Controlador.PlatoFondoWS.listarPlatoFondoRequest inValue = new Controlador.PlatoFondoWS.listarPlatoFondoRequest();
            inValue.Body = new Controlador.PlatoFondoWS.listarPlatoFondoRequestBody();
            Controlador.PlatoFondoWS.listarPlatoFondoResponse retVal = ((Controlador.PlatoFondoWS.Plato_FondoWSSoap)(this)).listarPlatoFondo(inValue);
            return retVal.Body.listarPlatoFondoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Controlador.PlatoFondoWS.listarPlatoFondoResponse> Controlador.PlatoFondoWS.Plato_FondoWSSoap.listarPlatoFondoAsync(Controlador.PlatoFondoWS.listarPlatoFondoRequest request) {
            return base.Channel.listarPlatoFondoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Controlador.PlatoFondoWS.listarPlatoFondoResponse> listarPlatoFondoAsync() {
            Controlador.PlatoFondoWS.listarPlatoFondoRequest inValue = new Controlador.PlatoFondoWS.listarPlatoFondoRequest();
            inValue.Body = new Controlador.PlatoFondoWS.listarPlatoFondoRequestBody();
            return ((Controlador.PlatoFondoWS.Plato_FondoWSSoap)(this)).listarPlatoFondoAsync(inValue);
        }
    }
}
